### ISSUE TITLE
Align roll, pitch, yaw definition with Carla

### ISSUE THREAD

**Issue by thomasfermi** [thomasfermi/Algorithms-for-Automated-Driving#19]
Definition of roll, pitch, yaw in Carla is given [here](https://carla.readthedocs.io/en/0.9.11/python_api/#instance-variables_43). The order seems to be yzx, which is different from zyx which is used in the book. This **might** be a problem.

I think the exercise video and exercise image should have the camera mounted with yaw != 0. Then we could empirically check if the book's formula gives us the correct pitch and yaw, or if we have to change it to the yzx convention.

**Comment by thomasfermi** [comment]
I rechecked Carla's documentation and it is not very detailed, and to me it was even misleading. I did some analysis and wrote down how roll, pitch, yaw are handled in Carla [here](https://github.com/carla-simulator/carla/issues/2516).

This knowledge should help to work on this issue.

**Comment by thomasfermi** [comment]
Did some analysis and I think the rotation matrix in the book needs to be 

![image](https://user-images.githubusercontent.com/30798048/122268076-ee884600-cedb-11eb-9ade-2957703c4839.png)

(c=cos(), s=sin(), y=yaw, p=pitch, r=roll)

Problem with the matrix that is currently in the book is that it uses the ISO8855 coordinate system and not the camera reference system. I think that the formula in the book for getting yaw and pitch only works as an accident when yaw=0. The correct formula (if I am not mistaken) should be pitch = arccos(r3_z) and yaw = arctan(r3_y/r3_x). I will need some time to verify this with Carla. If it is true, I will write a more detailed explanation.

**Comment by thomasfermi** [comment]
The code that was checked in for issue #20 solves this for the lane detection chapter. The rotation matrix from my post above is now in the lane detection chapter.

The calibration chapter will need to be rewritten such that it makes use of the new text in the lane detection chapter.

**Comment by jiheddachraoui** [comment]
> Did some analysis and I think the rotation matrix in the book needs to be
> 
> ![image](https://user-images.githubusercontent.com/30798048/122268076-ee884600-cedb-11eb-9ade-2957703c4839.png)
> 
> (c=cos(), s=sin(), y=yaw, p=pitch, r=roll)
> 
> Problem with the matrix that is currently in the book is that it uses the ISO8855 coordinate system and not the camera reference system. The correct formula (if I am not mistaken) should be pitch = arcsin(r3_y) and yaw = -arctan(r3_x/r3_z). So the negative of what we have so far. I will need some time to verify this with Carla. If it is true, I will write a more detailed explanation.

@thomasfermi hello so i use directly this matrix? i have transformation matrix and i want to calculate pitch,yaw,roll
