### ISSUE TITLE
why the rotation formula no same with wikipedia 

### ISSUE THREAD

**Issue by rmGFW** [thomasfermi/Algorithms-for-Automated-Driving#30]
hi , this is a very nice book ; 

i was confused when reading chapter of  Camera Calibration , 

<img width="885" alt="image" src="https://user-images.githubusercontent.com/66858140/200024531-26ff19e4-4b73-4cb1-9c4d-517537b31878.png">

this matrix seems that no same with below  (from https://en.wikipedia.org/wiki/Rotation_matrix)

<img width="915" alt="image" src="https://user-images.githubusercontent.com/66858140/200024727-868e0882-8d9f-4fe2-9bd4-e08677d5d030.png">

**Comment by thomasfermi** [comment]
Hi @rmGFW, sorry for the late reply. These rotation matrices are always a pain. Everybody has different conventions. We tried to go for one that is compatible wit the CARLA simulator. 

One difference to Wikipedia is that we call pitch $\alpha$, yaw $\beta$, roll $\gamma$ and Wikipedia yaw $\alpha$, pitch $\beta$, roll $\gamma$. Then also which rotation is around the x,y,z axis is different. Compare the pitch matrix from Wikipedia with the pitch matrix from the [book](https://thomasfermi.github.io/Algorithms-for-Automated-Driving/LaneDetection/CameraBasics.html#yaw-pitch-and-roll-rotations). Everybody has different conventions :/ But the concept is the same :)
