### ISSUE TITLE
miss (Xw,Yw,Zw,1) in the middle of eqution (4)

### ISSUE THREAD

**Issue by dufengit** [thomasfermi/Algorithms-for-Automated-Driving#31]
miss (Xw,Yw,Zw,1) in the middle of eqution (4), link below
https://thomasfermi.github.io/Algorithms-for-Automated-Driving/LaneDetection/CameraBasics.html

**Comment by thomasfermi** [comment]
Thanks @dufengit! I recently fixed this.
