### ISSUE TITLE
Minor errata on page /Control/BicycleModel.html

### ISSUE THREAD

**Issue by very-serious-dev** [thomasfermi/Algorithms-for-Automated-Driving#37]
I think the line that states:

> From the triangle in [Fig. 22](https://thomasfermi.github.io/Algorithms-for-Automated-Driving/Control/BicycleModel.html#icr-construction) we find

Should actually refer to Fig. 25 (not 22)

**Comment by thomasfermi** [comment]
Thanks a lot @very-serious-dev :D !
