### ISSUE TITLE
questions about collect_data.py

### ISSUE THREAD

**Issue by liantao-genius** [thomasfermi/Algorithms-for-Automated-Driving#6]
Hi, Mario. Really thanks for your great work. I learned a lot from your book. I'd like to ask you a tiny question. In the Lane Boundary Projection:'Getting images is easy with Carla: We can attach a camera to a vehicle and store the image that this camera takes. If you want to see details, you can check out collect_data.py'. Could you please tell me where I can find this collect_data.py. I couldn't find it in your repository.

**Comment by thomasfermi** [comment]
Hi  @liantao-genius ! I'm glad you liked the book :)

You can find that script [here](https://github.com/thomasfermi/Algorithms-for-Automated-Driving/blob/master/code/solutions/lane_detection/collect_data.py).
Be sure to run it like it is specified in the [book](https://thomasfermi.github.io/Algorithms-for-Automated-Driving/LaneDetection/Segmentation.html#gathering-training-data) (click on "generate data yourself"):
`cd Algorithms-for-Automated-Driving `
`conda activate aad `
`python -m code.solutions.lane_detection.collect_data`

The section of the book that mentions the python script should have a link to that script. There are probably other parts in the book where such a link would be nice. I will look into this, once I find the time. The issue can be closed once this is done.
